version: '3.8'

services:

  mongo:
    container_name: mongo
    image: mongo:6.0.3
    environment:
      - MONGO_DATABASE="cooking_data"
    ports:
      - 27017:27017
    volumes:
      - ./db/data/db:/data/db
    networks:
      - myNetwork

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - myNetwork

  api:
    container_name: api
    environment:
      - MONGO_URL=mongodb://mongo:27017/articles
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - myNetwork

networks:
  myNetwork:
    name: myNetwork
    driver: bridge
